mysql:
    image: mysql:5.7.20
    container_name: mysql
    ports:
        - "3306:3306"
    volumes:
        - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    environment:
        - MYSQL_ROOT_PASSWORD=mysql@2017
        - MYSQL_ROOT_HOST=%
    restart: always
    
redis:
    image: redis:4.0.2
    container_name: redis
    ports:
        - "6379:6379"
    volumes:
        - ./redis/redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: always

django:
    image: registry.cn-hangzhou.aliyuncs.com/jerrygaoyang/django
    ports:
        - "9001:9001"
        - "3000:3000"
    container_name: django
    volumes:
        - ./projects:/opt/projects
        - ./supervisor/supervisord.conf:/etc/supervisord.conf
    restart: always
    
nginx: 
    image: nginx:1.13.5
    ports:
        - 80:80
        - 433:433
    container_name: nginx
    volumes:
        - ./nginx:/etc/nginx/conf.d
    restart: always
    
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - mysql:db
    ports:
        - 8000:80
    environment:
        - PMA_HOST=db
        - PMA_PORT=3306
    restart: always
